### ISSUE TITLE
Readthedocs autogenerated preview links to a 404 error page

### ISSUE THREAD

**Issue by ulya-tkch** [readthedocs/actions#24]
When I try and add a github action following the steps outlined in https://github.com/readthedocs/actions/tree/v1/preview the autogenerated description preview links to a 404 error page.

On readthedocs.io I have **Build pull requests for this project** turned on, my project is public and the project slug is my project's slug on readthedocs.io. What could be causing this issue?

My github action looks like below:

```
name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
    # Execute this action only on PRs that touch
    # documentation files.
    # paths:
    #   - "docs/**"

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "my project slug"

```
