### ISSUE TITLE
preview generates incorrect link

### ISSUE THREAD

**Issue by edublancas** [readthedocs/actions#31]
Hi,

I have a private project that uses readthedocs.com for building docs. I enabled previews by adding the following:

```yaml
name: Read the Docs Pull Request Preview
on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          platform: business # I thought this would fix it but it didn't
          project-slug: slug
```

PRs are correctly triggering documentation preview but the generated link added in the top comment looks like this:

📚 Documentation preview 📚: https://slug--number.org.readthedocs.build/en/68/

I noticed that manually changing the `.org` -> `.com` fixes the issue:

📚 Documentation preview 📚: https://slug--number.com.readthedocs.build/en/68/

Am I doing something wrong or is this a bug?
