### ISSUE TITLE
PR description not created on push of documentation files

### ISSUE THREAD

**Issue by stevepiercy** [readthedocs/actions#41]
First, when a pull request is opened and it contains documentation files as defined in the GitHub workflow defined below, the pull request's description updates with a link to the pull request preview build. This is good.

```yml
name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
    # Execute this action only on PRs that touch
    # documentation files.
    paths:
      - "docs/source/**"
      - .readthedocs.yaml
      - requirements-docs.txt
```

However, if there are no documentation files when the pull request is opened, but later documentation files are pushed to the pull request in subsequent commits, then the action does not run and the description is not updated. I assume many developers write code first, then later add documentation to their pull request if they add it at all.

It would be good to update the documented example workflow file to run on both `pull_request_target` and `push`. Unfortunately I don't know how to do that.

I tried moving it into [`jobs.<job_id>.if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif), but I quickly got lost in the syntax.
